# Generated by Django 3.0 on 2020-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
    ]
