# Generated by Django 3.0.3 on 2020-02-23 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0003_virtualmachine_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='root_fb',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_fb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='user_fb',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fb', to=settings.AUTH_USER_MODEL),
        ),
    ]
