# Generated by Django 3.0.3 on 2020-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20200223_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='value',
            field=models.CharField(max_length=1255, null=True),
        ),
    ]
