# Generated by Django 3.0.3 on 2020-03-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20200302_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('task_id', models.UUIDField()),
                ('vm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm', to='panel.VirtualMachine')),
            ],
        ),
    ]
