# Generated by Django 3.0.3 on 2020-03-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_simplequeue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequeue',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
