# Generated by Django 3.0 on 2020-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(default='test message subject', max_length=255),
            preserve_default=False,
        ),
    ]
