# Generated by Django 3.0 on 2020-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_virtualmachine_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
