# Generated by Django 3.0 on 2020-01-24 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 18, 10, 46, 625074)),
        ),
    ]
