# Generated by Django 3.0 on 2020-01-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20200126_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
