# Generated by Django 3.0 on 2020-02-02 14:48

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0009_auto_20200126_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(max_length=10)),
                ('user_flag', models.CharField(max_length=32)),
                ('root_flag', models.CharField(max_length=32)),
                ('disk_location', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('network_name', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('root_owned', models.ManyToManyField(blank=True, related_name='root_owned', to=settings.AUTH_USER_MODEL)),
                ('user_owned', models.ManyToManyField(blank=True, related_name='user_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
